# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Huy Nguyen
title: Mobile Developer
email: huynn109@gmail.com
website: huynn109.me

# Social links
#twitter_username: jekyll
github_username:  huynn109
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: huynn109
# pinterest_username: jekyll
#youtube_username: huynn109
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Huy and I'm a mobile developer. As well as mobile dev I also have experience making mobile apps and small restful api. I have worked at a number of companies gaining teamwork skills.

  I am most skilled in: <mark>Android</mark> and <mark>Flutter</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Football
   - Gaming
   - Technology

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
